.\python.exe -m pip uninstall antlr4-python3-runtime==4.8 -y
.\python.exe -m pip uninstall bitarray==2.5.1 -y
.\python.exe -m pip uninstall cffi==1.15.1 -y
.\python.exe -m pip uninstall click==8.1.3 -y
.\python.exe -m pip uninstall colorama==0.4.5 -y
.\python.exe -m pip uninstall Cython==0.29.30 -y
.\python.exe -m pip uninstall Flask==2.1.2 -y
.\python.exe -m pip uninstall Flask-Cors==3.0.10 -y
.\python.exe -m pip uninstall hydra-core==1.0.7 -y
.\python.exe -m pip uninstall importlib-metadata==4.12.0 -y
.\python.exe -m pip uninstall importlib-resources==5.8.0 -y
.\python.exe -m pip uninstall itsdangerous==2.1.2 -y
.\python.exe -m pip uninstall Jinja2==3.1.2 -y
.\python.exe -m pip uninstall MarkupSafe==2.1.1 -y
.\python.exe -m pip uninstall numpy==1.23.0 -y
.\python.exe -m pip uninstall omegaconf==2.0.6 -y
.\python.exe -m pip uninstall portalocker==2.4.0 -y
.\python.exe -m pip uninstall pycparser==2.21 -y
.\python.exe -m pip uninstall pywin32==304 -y
.\python.exe -m pip uninstall PyYAML==6.0 -y
.\python.exe -m pip uninstall regex==2022.6.2 -y
.\python.exe -m pip uninstall sacrebleu==2.1.0 -y
.\python.exe -m pip uninstall sentencepiece==0.1.96 -y
.\python.exe -m pip uninstall six==1.16.0 -y
.\python.exe -m pip uninstall tabulate==0.8.10 -y
.\python.exe -m pip uninstall torch==1.12.0 -y
.\python.exe -m pip uninstall torchaudio==0.12.0 -y
.\python.exe -m pip uninstall tqdm==4.64.0 -y
.\python.exe -m pip uninstall typing-extensions==4.3.0 -y
.\python.exe -m pip uninstall Werkzeug==2.1.2 -y
.\python.exe -m pip uninstall zipp==3.8.0 -y
.\python.exe -m pip uninstall requests==2.28.1 -y
.\python.exe -m pip uninstall py7zr -y
.\python.exe -m pip uninstall ctranslate2 -y